name: BATS Tests

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye-slim
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y bats id3v2

      - name: Run Bats tests
        run: |
          bats tests/
